### ISSUE TITLE
[BUG] Half animals in water

### ISSUE THREAD

**Issue by Djan0106** [ZAWA-Evolved/ZAWA#14]
When some animals get in water, they underwater body's part gets invisible
![2022-03-01_21 58 40](https://user-images.githubusercontent.com/100729529/156263496-7dbb292d-758d-4a6c-91ad-3b3a469974d5.png)
Note: I'm using a clearer water resource pack, but animals gets invisible even without it.

- Minecraft 1.16.5
- Forge 36.2.29
- Zoo and Wild Animals: Evolved (first release)

**Comment by Mnesikos** [comment]
This does not happen with just ZAWA, what else are you using besides ZAWA and this resource pack? Any shaders? Does the same thing happen with vanilla entities?

**Comment by Djan0106** [comment]
I'm using some other mods, but not any shaders. Any other animals do it.
But now I addded optifine and it seems correct

Il Mer 2 Mar 2022, 12:20 AM Mnesikos ***@***.***> ha scritto:

**Comment by Mnesikos** [comment]
I'm honestly not sure how this would be an issue with zawa, so I'm going to close this issue.
