### ISSUE TITLE
[BUG] Summoning animals bugs

### ISSUE THREAD

**Issue by Djan0106** [ZAWA-Evolved/ZAWA#15]
When I summon an animal then DataBook says that his favourite food is Air, and if I try to summon an animal with NBT {Variant:0} using a number which doesn't match any texture my game crashes.

- Minecraft 1.16.5
- Forge 36.2.29
- Zoo and Wild Animals: Evolved (first release)

**Comment by Mnesikos** [comment]
Unfortunately, the favorite food not being set up is an issue with the summon command not calling the rest of the NBT data when you only supply partial data. I will try to setup a part of the code to fix this if possible, however you can also add `FavoriteFood:` and a numerical item ID to the summon command's NBT data.

Incorrect variants no longer crash in **1.0.0-BeefBeta3**, instead you are just supplied with an empty texture.

**Comment by Djan0106** [comment]
Okay, no problem! In survival world animals spawn and you capture them, so it doesn't really matter if the summoned one have this bug, the other spawned naturally or with egg doesn't have it, and this is the important
