### ISSUE TITLE
[BUG] Tamed animals and enrichments

### ISSUE THREAD

**Issue by Djan0106** [ZAWA-Evolved/ZAWA#16]
Whrn I tame animals, they try to use enrichments or trough, and then they bug near the enrichment/trough, even if I remove it. For example, giraffes after I removed troughs

https://user-images.githubusercontent.com/100729529/156451665-89ce1bde-e36d-4d69-8d4d-a2eb7fdee034.mp4

- Minecraft 1.16.5
- Forge 36.2.29
- Zoo and Wild Animals: Evolved (first and second release)

**Comment by Mnesikos** [comment]
The video file attached doesn't seem to be working- could you try again, or try a different format?

**Comment by Djan0106** [comment]
I tried several time to post a video and it diden't work. Basically animals
go near enrichment/troughs and after they use it they start to spin, then
they move away a little e then return near the block and move in a strange
way. This hapoens even if you remove enrichments or troughs

Il Gio 3 Mar 2022, 12:30 AM Mnesikos ***@***.***> ha scritto:

**Comment by Mnesikos** [comment]
I'm going to go ahead and refer this issue to #22! (Feel free to repost there with the form provided, however it will not be necessary.)

**Comment by Djan0106** [comment]
Yes, I'm going to check which animals do that bug. I'm sure about kangaroos
and giraffes, I don't know about others, I will check

Il Ven 4 Mar 2022, 8:36 PM Mnesikos ***@***.***> ha scritto:
