### ISSUE TITLE
Overlapping/static-y textures?

### ISSUE THREAD

**Issue by bigfoot102030** [ZAWA-Evolved/ZAWA#17]
Hey! I was just testing out the mod and I'm not sure if this is something intentional or unavoidable, but in some of the animal models I've noticed these static-y textures that you get when things overlap. I've only noticed it on the praying mantis antennae and the spider monkey tail.
![2022-03-02_19 58 13](https://user-images.githubusercontent.com/92448774/156475840-8e31cb29-f93b-4a23-97b4-b4847334c1bb.png)
![2022-03-02_19 58 41](https://user-images.githubusercontent.com/92448774/156475841-eacaf05a-69f8-401b-928d-51559b62da4a.png)
 It might be hard to tell in the images, but the tail of the spider monkey and the antennae of the praying mantis both have that glitchy texture I mentioned.

**Comment by kmfisk** [comment]
yep, this is called z-fighting, or texture overlapping. it happens when two planes of different pieces overlap.

we work around it on some models, but on pieces like this it's not something i'm too worried about. known issue, might fix if i have time, but not an error or unintended behavior.
