### ISSUE TITLE
[BUG] Prickly pear cactus drop

### ISSUE THREAD

**Issue by Djan0106** [ZAWA-Evolved/ZAWA#20]
Prickly pear cactus don't drop their fruit, I can't get them even if I put the plant in the crafting table

- Minecraft 1.16.5
- Forge 36.2.29
- Zoo and Wild Animals: Evolved (third release)

**Comment by Mnesikos** [comment]
Also not a bug! Please, please read the wiki.
<https://github.com/ZAWA-Evolved/ZAWA/wiki/Plants#prickly-pear-cactus>

**Comment by Djan0106** [comment]
My fault! So sorry, I know it's frustrating when someone report bugs
without reading wiki before, I will check it better next time!

Il Gio 3 Mar 2022, 11:45 PM Mnesikos ***@***.***> ha scritto:
