### ISSUE TITLE
[BUG] Mussel Box Texture Error

### ISSUE THREAD

**Issue by legoman97724** [ZAWA-Evolved/ZAWA#23]
The water in the mussel box texture appears gray when in your inventory or hand.

![musselbox](https://user-images.githubusercontent.com/100726742/156883732-0ea0dc92-53b3-44f1-8e63-a6c5db73b80c.png)

 - Minecraft 1.16.5
 - Forge 36.2.20
 - ZAWA BeefBeta4
 - No other mods

**Comment by Mnesikos** [comment]
Going to close this, as it's not truly an issue. There doesn't seem to be a way to color water for items, if anything we can remove the water from the item model.
