### ISSUE TITLE
[BUG] Net Launcher

### ISSUE THREAD

**Issue by Jmaster77red** [ZAWA-Evolved/ZAWA#29]
Insects die when netted by a slingshot net, possibly fish as well, havent tried.
Loads up slingshot nets with animals already in them (based on where the nets are in your inventory)
Sometimes it doesnt load nets when you have spare ones ( i think its based on what type of mobs you have already netted as well as where your standing, because it never works on trapdoors).

**Comment by Mnesikos** [comment]
In the future, either open a new issue for separate bugs or at least organize them into a proper list.

1. Damage is intended. Insects have low health and should be captured by other means.
2. Definitely a bug. Thanks!
3. This could use its own issue thread **using the format provided,** including screenshots and a list of instances the loading doesn't work.

**Comment by Mnesikos** [comment]
"Loads up slingshot nets with animals already in them" fixed with release **1.0.0-BeefBeta5**.
