### ISSUE TITLE
many bug

### ISSUE THREAD

**Issue by Emotta4825** [ZAWA-Evolved/ZAWA#30]
First of all I would like to thank you for having released the mod in 1.16.5 but I noticed a lot of problems. first is the fact that baby animals do not grow up, then there are the feeders that do not work and that we do not have access to the water and snow sprayer because it does not work 

Please correct them quickly or I won’t be able to play with them.

**Comment by Mnesikos** [comment]
First of all, please use the bug issue template that was provided.

Baby animals do grow up, they take longer than vanilla animals. Read the wiki page here for information: https://github.com/ZAWA-Evolved/ZAWA/wiki/Animal-breeding#growth-times

Feeders work as far as I can tell, if you can open a proper issue report with proper information on what isn't working, I'll be able to assist further.

The sprinkler's functionality is simply not implemented yet, so this is also not a bug. It will be implemented in a later version.

**Comment by kmfisk** [comment]
please do not ask our coder to "work quickly." if you would like us to work in a rush, please send $50 to my house through overnight express mail so i can wave it in mnesikos's face.

if you want this report to be helpful, you will need to add more details. please send your mod list, what version of the mod + forge you are using, as well as screenshots of problems. we will need to know if you are on singleplayer or multiplayer. some multiplayer functionality is not thoroughly tested and we appreciate specific server issue reports.

"feeders do not work" is not a helpful report, they are known and tested to be usable by animals for all intents and purposes. you will need to specify what is not working about them. are items not rendering properly? are animals not eating from them? we cannot fix problems unless we know what they are and exactly what is going on.

please either edit or add on to your report. entitled, un detailed reports do nothing to help the mod or team.
