### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Emotta4825** [ZAWA-Evolved/ZAWA#31]
hello I’m a fan of your mod but I find that there are missing animals . I know you don’t want any animal suggestions but I wanted to ask you if afterwards you could integrate into the mod the old animals that are in the ZAWA mod in 1.12.2

please do not delete my message and consider my suggestions 
thank you: Emotta

**Comment by kmfisk** [comment]
since vintagebeef paid me about $400 to make the assets for the animals in the beef beta, i am calculating that you will need to send me about $2500 for just the first batch of ZAWA rebuilt 1.0 animals. please postmark this to "professor hugecock, md" and overnight it to my address at your expense.
