### ISSUE TITLE
Koalas wont drink from water source

### ISSUE THREAD

**Issue by squidprobe21** [ZAWA-Evolved/ZAWA#33]
Koalas refuse to drink from water source blocks but are just fine with drinking from water bowls
![2022-03-23_14 29 05](https://user-images.githubusercontent.com/81724975/159819023-c47c94cf-3ae5-42b0-a4e8-7b2675ff7ab3.png)
easily recreated by just trapping a koala next to a water source block
using the omegamc zawa 1.1.4 pack beta
also noticed some problems with there ai where they will just wander around in circles till they either die or you relog but i wasnt able to get video of it because my recording software is broken and im not sure how to recreate it since idk the cause.

**Comment by Mnesikos** [comment]
Referring you to #22, but also this should be fixed with version **1.0.0-BeefBeta5** which was just released a moment ago, so please wait until the Omega team is able to update the modpack!

**Comment by squidprobe21** [comment]
ah ok thanks! had no clue that it just updated!
