### ISSUE TITLE
Data Book Diet Not Viewed Properly With Other Mods

### ISSUE THREAD

**Issue by WhyNotM3** [ZAWA-Evolved/ZAWA#34]
When using Pam's Harvestcraft, the diet section of the book is not always fully viewable on animals such as the Macaw. The diet will extend off the book and not everything can be seen.

![2022-03-25_18 39 48](https://user-images.githubusercontent.com/102398551/160222568-a99df03b-b577-48b2-abc1-e8aa26d22c25.png)

 Minecraft 1.16.5
 Forge 36.2.26
 ZAWA 1.0.0 BeefBeta5
 Pam's Harvestcraft

**Comment by WhyNotM3** [comment]
I just realised that I do have other mods that add mostly tree items that also cause the data book to look like this. If Its helpful, I can go through my mods and list them all

**Comment by Mnesikos** [comment]
That's alright, you don't have to! I just haven't added a scrolling box for these yet. 😆 Thank you though!

**Comment by Mnesikos** [comment]
This is now fixed in our dev space, and will be out in the next update! ❤️
