### ISSUE TITLE
[BUG] Cichlid change color in buckets

### ISSUE THREAD

**Issue by Tinuqin** [ZAWA-Evolved/ZAWA#36]
When picking up a (named) african lake cichlid with a bucket and then releasing it again, the cichlid has a different color/type. Did not try to reproduce with other types of fish or unnamed fish.

 - Minecraft 1.16.5
 - Forge 36.2.20
 - OmegaMC ZAWAEvolved modpack 1.1.5 (contains BeefBeta5)

**Comment by Mnesikos** [comment]
Fixed with the release of **1.0.0-BeefBeta6**, thanks for reporting! ❤️
