### ISSUE TITLE
Book

### ISSUE THREAD

**Issue by Taknax** [ZAWA-Evolved/ZAWA#37]
**!! ANIMAL SUGGESTIONS ARE NOT PERMITTED AND WILL BE DELETED !!**

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
No problem or issue.

**Describe the solution you'd like**
Patchouli books could be used for the ingame book.

**Describe alternatives you've considered**
An alternative could be to code the book, but it would not have the P. features.

**Comment by Mnesikos** [comment]
We have no interest in using patchouli.
