### ISSUE TITLE
[BUG] Bugs/Insects not spawning

### ISSUE THREAD

**Issue by Myrkis** [ZAWA-Evolved/ZAWA#38]
**Describe the bug**
Bugs/Insects are not spawning in my local world. But the ZAWA fish and rats are spawning (rarely though).
My world seed: 7118515678452751555

**To Reproduce**
Steps to reproduce the behavior: I have no idea

**Expected behavior**
I would expect the bugs, i.e. butterflies, spiders, etc. to spawn

**Versions (please complete the following information):**
 - Minecraft 1.16.5
 - Forge 36.2.33
 - ZAWA 1.0.0-BeefBeta6
 
 - list all other mods associated with the pack that crashed (a screenshot is okay)
- Advanced XRay (Forge Edition) 2.7.0
- Apotheosis 4.8.99C
- AppleSkin 2.4.0
- Architectury API (Forge) 1.31.59
- Bad Mobs 9.0.6
- Bookshelf 10.4.32
- Botany Pots 7.1.33
- Botany Trees 3.0.7
- Caged Mobs 1.3.8
- Chipped 1.2.1
- Clumps 6.0.0.28
- ConnectedTexturesMod 1.1.2.6
- Easy Piglins 1.0.2
- Easy Villagers 1.0.13
- Enchantment Descriptions 7.0.19
- Explorer's Compass 1.1.2
- ForgeEndertech 7.2.2.0-build.0202
- FTB Library (Forge) 1605.3.4-build.90
- FTB Ultimine (Forge) 1605.3.1-build.45
- Harvest 1.0.3
- Hwyla 1.10.11-B78_1.16.2
- Iron Chests 11.2.21
- JourneyMap 5.8.1
- Just Enough Items (JEI) 7.7.1.152
- Just Enough Resources (JER) 0.12.1.128
- Large Ore Deposits 4.1.9.2-build.0217
- More Storage Drawers 1.1.2
- Nature's Compass 1.9.1
- Oh The Biomes You'll Go 1.3.5
- Patchouli 53.2
- Placebo 4.7.0
- Polymorph (Forge) 0.40
- Refined Storage 1.9.17
- Refined Storage Addons 0.7.4
- Server Redirect 1.4.3
- Simple Farming 1.3.8
- Storage Drawers 8.5.1
- U Team Core 3.2.1.208
- Useful Backpacks 1.12.1.90
- Wawla - What Are We Looking At 8.0.9
- WorldEditCUI Forge Edition 3 3.0.9

**Additional context**
I have tried to start new worlds with different seeds, but still no bug spawns.
The "Bad Mobs" mod was added to stop hostile mobs from spawning (thought it might have been a mobcap issue). But no bugs spawn, even when I fly out into new, fresh unexplored chunks.
I have also tried to do create local worlds that only contain the mods from VintageBeef's Zoo server, but the bugs will not spawn there either. But they spawn all over the place on the server.

**Comment by Mnesikos** [comment]
There was a recent update to fix ZAWA's ambients to spawn and despawn the same as vanilla, so hopefully that's fixed this. Let me know! (Before this fix, ambients would spawn around the world's spawn point and never despawn which would take up the spawn count and not allow more of anything in the same category to spawn.)
