### ISSUE TITLE
[BUG] Short Issue Description

### ISSUE THREAD

**Issue by KeyesArc** [ZAWA-Evolved/ZAWA#39]
**Describe the bug**
Game crashing on startup, and shows the following error:
ZAWA: Evolved has failed to load
java.lang.NoClassDefFoundError: net/minecraftforge/commom/ForgeSpawnEggItem

**To Reproduce**
Starting the game

**Expected behavior**
I expected the game to launch normally.

**Logs (REQUIRED)**
Provide a link to a pastebin.com: https://pastebin.com/4rdD36QJ

**Screenshots**
  down bellow.

**Versions (please complete the following information):**
 - Minecraft 1.16.5
 - Forge 36.2.20
 - ZAWA most recent one, 1.0.0 beefbeta6
 - screenshot down bellow
![mods 1](https://user-images.githubusercontent.com/103838971/165198337-09f9c642-0052-43ce-889e-de8bdb9ae593.png)
![mods 2](https://user-images.githubusercontent.com/103838971/165198340-0ffa55ab-e40e-4207-b29a-f3cd7be0f2fb.png)
![mods 3](https://user-images.githubusercontent.com/103838971/165198342-cc004705-3ae2-4420-8239-e70b51c68869.png)

**Additional context**
![Erro](https://user-images.githubusercontent.com/103838971/165198011-a003ecac-e304-4412-931a-9808096658d8.png)

**Comment by Mnesikos** [comment]
Hi! According to your crashlog, you are using Forge 36.2.9, which is an earlier version than 36.2.20 (9<20... the file should have been labeled as 09, but what can you do lol)! Updating your forge version will fix this.
