### ISSUE TITLE
[BUG] Missing texture in animal data book

### ISSUE THREAD

**Issue by raininavada** [ZAWA-Evolved/ZAWA#4]
So when opening the book, we have the 17 animals, but if i click on either the Giraffe or the Hornbill the texture for the variant is missing. Here are the screenshots:

![2022-03-01_17 15 13](https://user-images.githubusercontent.com/100724695/156242591-a397b018-fd9e-4be8-9bcb-be6f6ec1440d.png)

^ Opened the giraffe entry on the book

![2022-03-01_17 15 19](https://user-images.githubusercontent.com/100724695/156242616-c833d94b-91c5-4075-86f5-718c897bb7d9.png)

^ Opened the Northern Giraffe variant entry, still the texture is missing.

![2022-03-01_17 15 31](https://user-images.githubusercontent.com/100724695/156242716-b15fbad1-be40-486f-a144-86327fa06383.png)

^ Same here with the hornbills

![2022-03-01_17 20 55](https://user-images.githubusercontent.com/100724695/156242790-5fcf6109-2e50-45ab-8de1-a6a2fff0c4ad.png)

^_For any confussion this is the Macaw entry with the textures showing_

**However the animal data book is reaaaaally a work of art, it's very detailed with all of the information for each variant thank you so much for it<3**
 
- Minecraft 1.16.5
 - Forge 36.2.29
 - ZAWA Evolved Beta
 - Only optifine installed

**Comment by kmfisk** [comment]
ope - just saw this! these textures are a work in progress and will be added soon. thank you for catching this!
