### ISSUE TITLE
Pandas and koalas eating any item

### ISSUE THREAD

**Issue by kmfisk** [ZAWA-Evolved/ZAWA#42]
as posted a few times in the fanchat, it looks like the item holding + eating mechanic is breaking diets.

if you hand any item to a panda or koala, they will eat it. this is an intended feature for bamboo (panda) and eucalyptus (koala) only, something probably got lost in translation there.

newest beef beta carnivora version.

**Comment by Mnesikos** [comment]
Fixed for Carnivora2's release
