### ISSUE TITLE
[BUG] Crafting issues thread for Fisk

### ISSUE THREAD

**Issue by kmfisk** [ZAWA-Evolved/ZAWA#44]
-zoo fence recipe uses STEEL BARS (block) instead of STEEL FENCE
-climbing vine recipe incorrectly uses two iron INGOT instead of one iron NUGGET

i'll fix these for the next beta.

**Comment by kmfisk** [comment]
-waste bins are not using the correct concrete colors. benches are.

**Comment by Mnesikos** [comment]
![Screenshot_20220528-115516_Chrome](https://user-images.githubusercontent.com/36017380/170833035-5ae6554c-e588-43ca-974b-652d11c81616.jpg)
Gonna drop this in here, assuming these are broken recipes as well. (Fences -> bar block should make 2 blocks according to text; and slabs should be crafted from full bar blocks not fences?)

**Comment by kmfisk** [comment]
yep, these are incorrect too. i'll go through and fix these for tropical ex.

**Comment by kmfisk** [comment]
vines + bars recipes fixed. waste bin recipes fixed. closing issue, if you guys see any more please report them!
