### ISSUE TITLE
"Animal Plaque"

### ISSUE THREAD

**Issue by CrystalRiver998** [ZAWA-Evolved/ZAWA#47]
**Describe the bug**
writting not visible to players that didnt place it. Does not work like a sign

**To Reproduce**
make, place and type an animal plague on server

**Expected behavior**
you can read it but other players cant

**Versions (please complete the following information):**
 - Minecraft 1.16.5
 - Forge 36.2.34
 - ZAWA-1.16.5-1.0.1-BeefBeta-Carnivora1

**Additional context**
![2022-05-30_01 19 27](https://user-images.githubusercontent.com/106496807/170895809-cc8d1492-fdab-4e54-8ee5-1d37d8f2a369.png)
![2022-05-30_01 19 29](https://user-images.githubusercontent.com/106496807/170895812-b0adc97d-0837-40eb-969c-e64a8c003cf4.png)
![2022-05-29_16 19 27](https://user-images.githubusercontent.com/106496807/170895820-58e296a7-8e62-418e-85d0-e5b3d90e0b36.png)

reported in discord- issue known

**Comment by CrystalRiver998** [comment]
![2022-05-30_02 26 40](https://user-images.githubusercontent.com/106496807/170897807-9c0d6063-52b0-42f9-a12d-f3521b910b56.png)
exited server and came back in, signs now blank

**Comment by Mnesikos** [comment]
Would like to merge this with issue #8
