### ISSUE TITLE
[BUG] Polar bear in data book has no face

### ISSUE THREAD

**Issue by trewshrew** [ZAWA-Evolved/ZAWA#50]
**Describe the bug**
One of my polar bears (name tagged but untamed) looks weird (no face) in the data book render.
After a relog it was still affected but also his companion was also affected.

**To Reproduce**
New creative world spawn a bunch of bears hit them with the data book and check the image.
Does not seems restricted by variant but might be more common on vanilla and french vanilla ??.
Seems pretty consistent that if I see no face then come back to the same animal later it will still be affected.

**Expected behavior**
See the bear as it is in the game with a face

**Logs (REQUIRED)**
no logs

**Screenshots**
![NoFace](https://user-images.githubusercontent.com/104867588/172000366-a2014a8b-4eab-4b77-8bd7-ed7d096f749f.png)

**Versions (please complete the following information):**
* Minecraft1.16.5
* Forge 36.2.35
* awa-1.16.5-1.0.1-BeefBeta-Carnivora2.jar
list all other mods associated with the pack that crashed (a screenshot is okay)
CTM-MC1.16.1-1.1.2.6.jar
OptiFine_1.16.5_HD_U_G8.jar
ServerRedirect-ForgeMC16-1.4.jar
WorldEdit-CUI-FE3-1.16.5-3.0.9.jar
byg-1.3.5.jar
chipped-1.16.5-1.2.1-forge.jar
jei-1.16.5-7.7.1.152.jar
journeymap-1.16.5-5.8.5.jar
litematica-forge-1.16.5-0.0.0-dev.20210917.jar
malilib-forge-1.16.5-0.10.0-dev.21+beta.1.jar
polymorph-forge-1.16.5-0.37.jar
replaymod-1.16.4-forge-1.0.1.jar
zawa-1.16.5-1.0.1-BeefBeta-Carnivora2.jar

**Additional context**
None

**Comment by Mnesikos** [comment]
This is the same as #5! Known issue, just hasn't been fixed yet.
