### ISSUE TITLE
[BUG] Spawn Egg Babies Not the Same Species

### ISSUE THREAD

**Issue by legoman97724** [ZAWA-Evolved/ZAWA#52]
This bug applies to animals with multiple species including Hornbills, Giraffes, Macaws, Spider Monkeys, and Flamingos. When you right-click on an adult animal to produce a baby animal, it might not spawn a baby of the same species. Ex. If you right-click on an adult Masai giraffe you might get a baby southern giraffe.

To reproduce, grab a spawn egg of one of the above-mentioned animals then right-click on it to spawn a baby animal. Then use the visual appearance or animal data book to see if the baby is a different species than the parent.

I would expect when you right-click on a certain species of animal to spawn a baby, it would be the same species. Ex. When you right-click on an American Flamingo, an American Flamingo baby should spawn, not another flamingo species.

 - Minecraft 1.16.5
 - Forge 36.2.20
 - ZAWA 1.0.1-BeefBeta-Carnivora2

 - Other Mods
 - World Edit 
 - Biomes O' Plenty
 - Dynamic Trees
 - Dynamic Trees BOP

**Comment by Mnesikos** [comment]
This should be fixed! (Reopen if it's not but I'm 99% sure it is? Lol)
