### ISSUE TITLE
[BUG] too many aquatic animals

### ISSUE THREAD

**Issue by panebraxd** [ZAWA-Evolved/ZAWA#53]
**Versions**
 - Minecraft 1.12.2
 - Forge 36.2.20
 - zawa-1.12.2-2.1.3

![image](https://user-images.githubusercontent.com/108436386/176555422-d8f7875a-21ee-41d5-b55a-b201672d0d5b.png)

**Comment by Mnesikos** [comment]
Rebuilt is discontinued and not supported, this issue tracker is for Evolved versions only.
