### ISSUE TITLE
Red Kangaroo Spawn In Savanna Biome

### ISSUE THREAD

**Issue by likknnjhoson** [ZAWA-Evolved/ZAWA#57]
**!! ANIMAL SUGGESTIONS ARE NOT PERMITTED AND WILL BE DELETED !!**

**Is your feature request related to a problem? Please 

> describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Mnesikos** [comment]
This is not how you fill out a github issue. Read through everything and try again.
