### ISSUE TITLE
No Freshwater Fish Spawns 

### ISSUE THREAD

**Issue by Mooonblaze** [ZAWA-Evolved/ZAWA#58]
Version: 1.16.5 Version 1.0.1 BeefBeta-Carnivora 2
Forge Version: 36.2.39

ZAWA is causing no freshwater fish to spawn in rivers. I have only ever seen one shoal of ZAWA salmon, and then I disabled the salmon spawning in the config to see if that would bring back vanilla salmon spawns because I prefer their frequent respawning. The ZAWA salmon never respawned when they were enabled (like vanilla fish often do) and after disabling them I still have no vanilla spawns. Squids ARE spawning as normal - they respawn in groups when they die. Even with them, rivers are very barren and sad. :(

An option to bring back vanilla fish spawning would be nice, even having them alongside ZAWA salmon. But if ZAWA salmon respawned like vanilla fish did, that would be nice as well.

**Comment by Mnesikos** [comment]
Not sure exactly what's going on with this or if it's still an issue. ZAWA doesn't disable any vanilla spawns, just adds spawns for the new animals. That does of course give vanilla fish less a chance of spawning, but it shouldn't be zero.

There was a recent update to fix ZAWA's ambients to spawn and despawn the same as vanilla, so hopefully that's fixed it? Let me know! (Before this fix, ambients would spawn around the world's spawn point and never despawn which would take up the spawn count and not allow more of anything in the same category to spawn.)
