### ISSUE TITLE
Zawa mobs barely spawning??

### ISSUE THREAD

**Issue by mo0nxi3** [ZAWA-Evolved/ZAWA#59]
Okay so I just created a world yesterday with a bunch of mods including the zawa mod. And while exploring this newer world I have only seen about 4 mobs from the zawa mod and a ton of vanilla cows and sheep. which is really weird because I was just playing with zawa rebuilt and I was seeing different zawa species in each biome, but now with zawa evolved I haven't.

Mind you I have already traveled thousands of blocks around this world, through all kinds of biomes with the biomes o' plenty and oh the biomes you'll go mods, and still I have only seen a few sea slugs, a spider monkey, and a carpenter bee. I saw a reddit post saying that you can potentially use a mod called "In Control," but I have no idea how to use it? So I would really appreciate some help!

 - Minecraft 1.16.5
 - Forge 36.2.21
 - ZAWA 1.0.1 Carnivora 2
 - all the mods I'm currently using are listed below
 ![Screenshot (2)](https://github.com/ZAWA-Evolved/ZAWA/assets/138801299/77ccd840-898d-482f-a4dd-aac6548ef5ff)

Thanks so much for any help that is provided!

**Comment by Mnesikos** [comment]
> I have already traveled thousands of blocks around this world

Does this mean you explored the world before adding zawa? If that's the case, new animals won't spawn in pre-generated (already explored) chunks, you would have to travel to new areas.

Other than that I'm not sure what to tell you. With the few animals in-game at the moment, they generally spawn as intended in vanilla, BOP, and BYG biomes. I have never used InControl myself, you would need to go to them for assistance there, or just up the spawn chances for zawa's animals in the [zawa config](https://github.com/ZAWA-Evolved/ZAWA/wiki/Configuration) to your liking.

**Comment by mo0nxi3** [comment]
I ended up clearing the config folder, because a few days ago I was playing 1.12.2 modded. Then restarting and making a new world and now it's working better!
