### ISSUE TITLE
[BUG] Flamingo group size is broken

### ISSUE THREAD

**Issue by LuzimBR** [ZAWA-Evolved/ZAWA#6]
flamingo group size in the data book is comically small

![image](https://user-images.githubusercontent.com/91569073/156247791-759ba9b8-9a11-4c1a-8943-142c22fdeef9.png)

UPDATE: sumatran orangutan group size too

**Comment by Mnesikos** [comment]
First off, you did not follow the bug report outline. Please do that in future reports.

Secondly, what's broken about this? This is the group range they spawn in the game, which is set through your spawn configs.

**Comment by PoetaCorvi** [comment]
the listed group size in the books is how many spawn in minecraft, not how many group together irl. some accuracy has to be sacrificed for the sake of performance, i dont think a lot of computers could handle spawn groups of hundreds of flamingos, and itd get pretty annoying if a group of a hundred tall pink birds spawned next to your house.
