### ISSUE TITLE
Fishing

### ISSUE THREAD

**Issue by Coldcoolr** [ZAWA-Evolved/ZAWA#61]
I think that casting a fishing rod with bait could trigger certain fish to bit, but certain fish would have certain bait to get them to bite, and the fish mob would bite it like the betweenlands 1.12.2 anadia, and maybe it could trigger a minigame to get it. I feel like fishing would be a fun way to collect fish for your aquariums and ponds.

**Comment by kmfisk** [comment]
not an issue. closed.
