### ISSUE TITLE
[BUG] Game crashes when I click singleplayer

### ISSUE THREAD

**Issue by Ryanisstillthesame** [ZAWA-Evolved/ZAWA#7]
**Describe the bug**
Zawa loads fine and minecraft loads fine, though when I click the singleplayer button my game immediately crashes.

**To Reproduce**
Clicking the singleplayer button
**Expected behavior**
Minecraft not to crash when clicking the singleplayer button

**Logs (REQUIRED)**
https://pastebin.com/FdTWPuAB   ----crash log
https://pastebin.com/KmGXWciE   ----debug
https://pastebin.com/DiwzwVAL    ----latest
**Screenshots**

**Versions (please complete the following information):**
 - Minecraft 1.16.5
 - Forge 36.2.25
 - ZAWA beefbeta1
 - list all other mods associated with the pack that crashed (a screenshot is okay)

**Additional context**
I am using MultiMC to install the mod so I am unsure if that has anything to do with the crash. Previously on other zawa versions I was able to run it fine with MultiMC and as such I am unsure.

**Comment by Mnesikos** [comment]
So currently this type of crash is known to happen only on certain launchers. MultiMC and GDLauncher are the only known ones at the moment, switching to another launcher should fix the issue.

**If anyone experiences this crash or similar on another launcher, please let us know here!**

Would definitely like to fix this issue for the launchers... but genuinely at a loss about it for now. Keeping this issue open for future reference.

**Comment by Tylermaster2** [comment]
This crash seems to happen with the default minecraft launcher for some reason too

**Comment by Mnesikos** [comment]
> This crash seems to happen with the default minecraft launcher for some reason too

Hm. Switching to the vanilla launcher solved the issue for me, however I'm realizing now that I'm still using the legacy launcher, not the microsoft store one. Which one were you using?

**Comment by Mnesikos** [comment]
If that still doesn't work for you, and you're able to, try the Curseforge launcher too. Hopefully.. one will work until we can get this fixed.

**Comment by SmithyMC** [comment]
Hi There, This is still a big issue on the Normal Minecraft Launcher. Minecraft Will Load but when the ZAWA Jar is added you cannot creat a world as it crashes and cannot load an exisitng new forge 1.16.5 World. I have tried with many different combinations using 8gb - 4gb and 2gb ram but makes no difference, Here are my Crash Reports both with and without any other mods of texture packs:

[crash-2022-03-02_18.08.28-client.txt Without mods or resource packs.txt](https://github.com/ZAWA-Evolved/ZAWA/files/8172220/crash-2022-03-02_18.08.28-client.txt.Without.mods.or.resource.packs.txt)

[crash-2022-03-02_18.02.51-client.txt - With Mods.txt](https://github.com/ZAWA-Evolved/ZAWA/files/8172221/crash-2022-03-02_18.02.51-client.txt.-.With.Mods.txt)

Yes this is the Real SmithyMC and was going to do a Showcase but sadly not yet

SmithyMC

**Comment by Mnesikos** [comment]
Thanks for the input, Smithy!! Honestly anything helps at this point because it works fine for some, and not so fine for others. I thought I pinned it down to the launchers, but here we are haha, doesn't make much sense anyways.

Do hold tight! We're working on it. Try whatever you can if you're up for it to get it working for you. Different launchers, brand new instances, maybe specifically forge 36.2.20. Sorry for the inconvenience!!

**Comment by SmithyMC** [comment]
No Problem. It's Really Really Weird bug and I have tried several versions of forge from 36.2.20 onwards and with all different settings as a long user of forge I know most of the pitfalls. It's beaten me this time but saw that a number of others having the same problem. Even tried not to use the mouse to try and create world but nothing for me and tried both versions of zawa 1.16.5 but still same problem and tried after clean computer reboot. I wait with anticipation as always keep up the Great Work! 😁
