### ISSUE TITLE
[BUG] Guns consume additional ammo

### ISSUE THREAD

**Issue by raininavada** [ZAWA-Evolved/ZAWA#9]
This happens on both Tranquilizer Gun with Tranquilizer Dart ammo and Net Launcher with Slingshot Net ammo.

I'm going to demonstrate it with the tranquilizer gun, but it happens the exact same with the net launcher

![2022-03-01_18 16 36](https://user-images.githubusercontent.com/100724695/156250546-31461e46-8339-4e8b-9f68-fecf5cd9d04e.png)

^ Notice i have 4 darts in my inventory

![2022-03-01_18 16 49](https://user-images.githubusercontent.com/100724695/156250853-0cb3c0b1-2704-4225-a15e-c08d8627847b.png)

^ I right clicked for around 2 seconds so it loads and it consumed 1 dart. Now the gun is supposedly loaded.

![2022-03-01_18 17 12](https://user-images.githubusercontent.com/100724695/156251069-3afaa5c4-d2f1-42e0-80db-9d639c4cb5b7.png)

^ I right clicked again just one time so it shoots, and it consumed 1 dart again and I'm pretty sure it isn't supposed to happen.

I would expect it to load and consume 1 dart, like it did, but not consume one again when it shoots, so it works like a normal vanilla crossbow. So in the end I waste 2 darts for shooting just 1.

Versions:
 - Minecraft 1.16.5
 - Forge 36.2.29
 - ZAWA Beefbeta
 - Only optifine installed

**Additional context**

**Comment by Mnesikos** [comment]
Huh! This is odd, I definitely did not notice this when I was testing around with them. Are you on a server or in single player?

**Comment by raininavada** [comment]
I was on singleplayer

**Comment by Mnesikos** [comment]
Just fixed this in our dev space! Will be seen in version **1.0.0-BeefBeta3**, thanks for reporting. ❤️
